name: CI

on:
  push:
    tags: 
      - v**
jobs:
  protoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order"]
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.23.7
      - uses: actions/checkout@v2
      - name: Etract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate Protoc
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com
    
