name: Protocol Buffer Go Stubs Generation
on:
  push:
    tags: 
      - v*
  workflow_dispatch:
permissions:
  contents: write
jobs:
  protoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.23.7
      - name: Etract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate Protoc
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/protoc.sh"
          ls -alh ${GITHUB_WORKSPACE}
          mkdir -p golang/${{matrix.service}}
          ./protoc.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com
    
